CREATE TABLE stars (
    star_id serial primary key,
    athyg_id integer unique,
    tycho2_id varchar(16) unique,
    gaia_dr3_id bigint unique,
    hyg_v3_id integer unique,
    hipparcos_id integer unique,
    henry_draper_id integer unique,
    harvard_yale_id integer unique,
    gliese_id varchar(16) unique,
    bayer_id varchar(16) unique,
    flamsteed_id integer unique,
    constellation char(3),
    proper_name varchar(64) unique,
    right_ascension numeric not null,
    declination numeric not null,
    pos_src varchar(16) not null,
    distance numeric not null,
    x0 numeric not null,
    y0 numeric not null,
    z0 numeric not null,
    distance_src varchar(16) not null,
    magnitude numeric not null,
    absolute_magnitude numeric not null,
    colour_index numeric,
    magnitude_src varchar(16) not null,
    radial_velocity numeric,
    radial_velocity_src varchar(16),
    proper_motion_right_ascension numeric,
    proper_motion_declination numeric,
    proper_motion_src varchar(16),
    velocity_x numeric,
    velocity_y numeric,
    velocity_z numeric,
    spectral_type varchar(16),
    spectral_type_src varchar(16),
    created_at timestamp default now(),
    updated_at timestamp default now()
);