name: Build and Release .NET App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Debug folder tree
        run: ls -R
      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./GalaxyWorld/galaxyworld/GalaxyWorld.Cli

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ./GalaxyWorld/galaxyworld/GalaxyWorld.Cli

      - name: Publish App
        run: dotnet publish --configuration Release --no-build --output ./publish
        working-directory: ./GalaxyWorld/galaxyworld/GalaxyWorld.Cli

      - name: Zip Published Output
        run: zip -r galaxyworld.zip ./GalaxyWorld/publish

      - name: Upload Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: galaxyworld
          path: galaxyworld.zip
          retention-days: 7

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: galaxyworld.zip
          asset_name: galaxyworld.zip
          asset_content_type: application/zip
